# goose配置
# [GooseBuild]和[GooseSearch]是框架所需要的配置信息
# 策略自定义的配置

[GooseBuild]
# 建库最多使用cpu个数.0表示设置为机器的cpu数
MaxProcs = 0

    # 建库数据库的相关配置
    [GooseBuild.DataBase]
    # 索引库的目标位置
    DbPath = "data/cse"
    # 正排转倒排的内存缓冲区最大容纳term数量.
    # 越大越好,减少读写磁盘数,随之内存占用越多.
    TransformMaxTermCnt = 10000000
    # 索引库最大id数
    MaxId = 5000000
    # 索引文件最大文件大小,单位(B),1G = 1073741824B
    MaxIndexFileSize = 1073741824
    # Data文件最大文件大小,单位(B),1G = 1073741824B
    MaxDataFileSize = 1073741824
    # 每个doc的Value大小,单位(B)
    ValueSize = 16

[GooseSearch]
# 检索最多使用cpu个数.0表示设置为机器的cpu数
MaxProcs = 0

    # 检索相关配置
    [GooseSearch.Search]
    # 检索并发协程数
    GoroutineNum = 1
    # 检索服务端口
    ServerPort = 7788
    # 接受请求的网络缓冲区(byte)
    RequestBufferSize = 1024
    # 发送请求的网络缓冲区(byte)
    ResponseBufferSize = 1048576

    # 更新相关配置
    [GooseSearch.Index]
    # 服务端口
    ServerPort = 7789
    # 接受请求的网络缓冲区(byte)
    RequestBufferSize = 10240

    # 定时刷新相关配置
    [GooseSearch.Refresh]
    # 每隔多少秒刷新一次
    SleepTime = 10


[Strategy]

# 调权字段个数
# 意味着输入doc的cse_value数组的元素个数必须是AdjustWeightFieldCount + 1
# 第一个元素是clusterid,剩下的是调权字段
# 另外ValueBoost的长度也必须是AdjustWeightFieldCount
# 表示每个字段生效的权重
AdjustWeightFieldCount = 6
# 调权参数的权重
ValueBoost = [0.03,0.08,0.05,0.03,0.10,1.00]


    # 建库策略
    [Strategy.Indexer]
        # 切词词典
        [Strategy.Indexer.Scws]
        xdbdict = "dict/dict.utf8.xdb"
        rules = "dict/rules.utf8.ini"

        # 赋权相关
        [Strategy.Indexer.Weight]
        MainTitleBoost = 1.0
        TitleBoost = 0.8
        KeyWordBoost = 0.9
    
    # 检索策略
    [Strategy.Searcher]
        # 切词词典
        [Strategy.Searcher.Scws]
        xdbdict = "dict/dict.utf8.xdb"
        rules = "dict/rules.utf8.ini"

        # 专名词典
        [Strategy.Searcher.TrieDict]
        # 先加载DictFile,如果加载失败,则读取DataFile转化为DictFile
        DataFile = "dict/name.txt"
        DictFile = "dict/name.dict"

